---
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      # Generall Stuff
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: end-of-file-fixer
        exclude: "^(.bumpversion.cfg|CHANGELOG.rst)$"
      # VCS
      - id: check-merge-conflict
      # Config / Data Files
      - id: check-yaml
      # Python
      - id: debug-statements
  # Python: check requirements
  - repo: https://github.com/peterdemin/pip-compile-multi
    rev: master
    hooks:
      - id: pip-compile-multi-verify
  # Python: flakes8 (syntax check with pyflakes only)
  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
        args:
          - "--select=F"
  # Python: reorder imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: master
    hooks:
      - id: reorder-python-imports
        args:
          - "--application-directories=.:src:tests"
  # Python: black
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  # Sweet formating with Prettier (HTML, JS, CSS, Markdownâ€¦)
  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier
